parameters:
    cardinity_client.controller.payment.class: Cardinity\ClientBundle\Controller\PaymentController
    cardinity_client.service.oauth_subscriber.class: GuzzleHttp\Subscriber\Oauth\Oauth1
    cardinity_client.service.stack.class: GuzzleHttp\HandlerStack
    cardinity_client.service.http_client.class: GuzzleHttp\Client
    cardinity_client.service.result_object_mapper.class: Cardinity\Method\ResultObjectMapper
    cardinity_client.service.exception_mapper.class: Cardinity\Http\Guzzle\ExceptionMapper
    cardinity_client.service.client_adapter.class: Cardinity\Http\Guzzle\ClientAdapter
    cardinity_client.service.client.class: Cardinity\Client
    cardinity_client.service.validator.class: Cardinity\Method\Validator
    cardinity_client.parameters.url: 'https://api.cardinity.com/v1/'
    cardinity_client.parameters.auth: 'oauth'
    cardinity_client.parameters.verify: false

services:
    cardinity_client.controller.payment:
        class: '%cardinity_client.controller.payment.class%'
        arguments:
            - '@templating'
            - '@router'
            - '@form.factory'
            - '@session'
            - '@cardinity_client.service.client'
            - '@service_container'

    cardinity_client.service.oauth_subscriber:
        class: '%cardinity_client.service.oauth_subscriber.class%'
        arguments:
            $config:
              token_secret: ''
              consumer_key: '%cardinity_client.consumer_key%'
              consumer_secret: '%cardinity_client.consumer_secret%'

    cardinity_client.service.stack:
        class: '%cardinity_client.service.stack.class%'
        factory: ['%cardinity_client.service.stack.class%', create]
        calls:
          - [push, ['@cardinity_client.service.oauth_subscriber']]

    cardinity_client.service.http_client:
        class: '%cardinity_client.service.http_client.class%'
        arguments:
            $config:
                base_uri: '%cardinity_client.parameters.url%'
                handler: '@cardinity_client.service.stack'
                auth: '%cardinity_client.parameters.auth%'
                verify: '%cardinity_client.parameters.verify%'

    cardinity_client.service.result_object_mapper:
        class: '%cardinity_client.service.result_object_mapper.class%'

    cardinity_client.service.exception_mapper:
        class: '%cardinity_client.service.exception_mapper.class%'
        arguments:
            $resultMapper: '@cardinity_client.service.result_object_mapper'

    cardinity_client.service.client_adapter:
        class: '%cardinity_client.service.client_adapter.class%'
        arguments:
            $client: '@cardinity_client.service.http_client'
            $mapper: '@cardinity_client.service.exception_mapper'

    cardinity_client.service.validator:
        class: '%cardinity_client.service.validator.class%'
        arguments:
            $validator: '@validator'

    cardinity_client.service.client:
        class: '%cardinity_client.service.client.class%'
        arguments:
            $client: '@cardinity_client.service.client_adapter'
            $validator: '@cardinity_client.service.validator'
            $mapper: '@cardinity_client.service.result_object_mapper'
